import { DEFAULT_FIELD_ORDER } from "./constants";
import { GlobalSettings, DEFAULT_CONFIG, ResumeData } from "@/types/resume";

export const initialGlobalSettings: GlobalSettings = {
  baseFontSize: 16,
  pagePadding: 32,
  paragraphSpacing: 12,
  lineHeight: 1.5,
  sectionSpacing: 10,
  headerSize: 18,
  subheaderSize: 16,
  useIconMode: true,
  themeColor: "#000000",
  pageBreakLinesVisible: true,
};

export const initialResumeState: Omit<ResumeData, "id" | "createdAt" | "updatedAt" | "templateId"> = {
  title: "小昊简历",
  basic: {
    name: "",
    title: "",
    email: "",
    phone: "",
    location: "",
    birthDate: "",
    gender: "",
    jobIntention: "",
    politicalStatus: "",
    showAge: true,
    fieldOrder: DEFAULT_FIELD_ORDER,
    icons: {
      email: "Mail",
      phone: "Phone",
      birthDate: "CalendarRange",
      location: "MapPin",
    },
    photoConfig: DEFAULT_CONFIG,
    customFields: [],
    photo: "",
  },
  education: [
    {
      id: "1",
      school: "",
      major: "",
      degree: "",
      startDate: "",
      endDate: "",
      visible: true,
      description: "",
    },
  ],
  skillContent: "",
  selfEvaluationContent: "",
  experience: [
    {
      id: "1",
      company: "",
      position: "",
      startDate: "",
      endDate: "",
      isPresent: false,
      visible: true,
      details: "",
    },
  ],
  certificatesContent: "",
  internship: [],
  draggingProjectId: null,
  projects: [
    {
      id: "p1",
      name: "",
      role: "",
      startDate: "",
      endDate: "",
      isPresent: false,
      description: "",
      visible: true,
    },
  ],
  menuSections: [
    { id: "basic", title: "基本信息", icon: "User", enabled: true, order: 0 },
    { id: "education", title: "教育背景", icon: "GraduationCap", enabled: true, order: 1 },
    { id: "skills", title: "专业技能", icon: "Zap", enabled: true, order: 2 },
    { id: "experience", title: "工作经历", icon: "Briefcase", enabled: true, order: 3 },
    { id: "internship", title: "实习经历", icon: "Laptop", enabled: true, order: 4 },
    { id: "projects", title: "项目经历", icon: "Rocket", enabled: true, order: 5 },
    { id: "certificates", title: "荣誉证书", icon: "Award", enabled: true, order: 6 },
    { id: "selfEvaluation", title: "自我评价", icon: "FileText", enabled: true, order: 7 },
  ],
  activeSection: "basic",
  customData: {},
  globalSettings: initialGlobalSettings,
};
